package GUI.resources;

public enum ImageIdentifier {
    ICON,
    BACKGROUND,

    PAWN_BLACK,
    LANCE_BLACK,
    BISHOP_BLACK,
    SILVER_GENERAL_BLACK,
    GOLD_GENERAL_BLACK,
    KING_BLACK,

    PAWN_BLACK_PROMOTED,
    LANCE_BLACK_PROMOTED,
    BISHOP_BLACK_PROMOTED,
    SILVER_GENERAL_BLACK_PROMOTED,

    PAWN_WHITE,
    LANCE_WHITE,
    BISHOP_WHITE,
    SILVER_GENERAL_WHITE,
    GOLD_GENERAL_WHITE,
    KING_WHITE,

    PAWN_WHITE_PROMOTED,
    LANCE_WHITE_PROMOTED,
    BISHOP_WHITE_PROMOTED,
    SILVER_GENERAL_WHITE_PROMOTED,
}
